DELETE http://localhost:3002/api/blogs/5dcf7ba8f4eea69c90545657
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVkY2Y2ODNkNzRiOWUwNjEwNDU0OWVmYiIsImlhdCI6MTU3Mzg3Njc4OH0.9IRFBzbl9afv7HZ1wO8Ri4SYIbSNDASRAqyd9kQDvQs

###

DELETE http://localhost:3001/api/persons/invalid